### PR TITLE
Dt/clean arch

### PR DESCRIPTION
**Pull request by nabond251**
**What I have done and why**

Updated `dt/clean-arch` from latest main [85129e](https://github.com/android/nowinandroid/commit/85129e4660f7a27c7081f4ac21169d19db89fbb6) so that it can continue to be a useful, up-to-date reference in exploring Clean Architecture per #1277 and #1273.

It does not look like tests are currently all passing.  Possible I'm not configured correctly.  In my dev environment, I have above main passing 70/133 tests; prior dt/clean-arch passing 61/120 tests; I'm thinking that's roughly parity with my updates passing 63/106?

### CODE REVIEW

**Comment by JackEblan** [comment]
This really needs a bigger refactoring just to compliment the Clean Architecture.

`:core:analytics`
`:core:data`
`:core:data-test`
`:core:database`
`:core:datastore`
`:core:datastore-test`
`:core:datastore-proto`
`:core:screenshot-testing`
`:core:ui`
`:core:network`
`:core:notifications`
`:core:testing`

Are part of the **Infrastructure Layer** and we need to move these outside of the core.

Also, there are some Android Frameworks included in the Data layer [util](https://github.com/android/nowinandroid/tree/main/core/data/src/main/kotlin/com/google/samples/apps/nowinandroid/core/data/util) and we need to move these Android Frameworks into a separate modules, just being outside of the `:core'

I'm not sure if they're going to like this.

**Comment by nabond251** [comment]
@JackEblan thanks for the feedback.  Just for context (which should have probably been provided in the opening line, my bad/will edit), I'm looking to update not main proper but #1277, which is an exploration of clean architecture prompted by #1273.  Neither that nor this are full and final statements on Clean Architecture proper, otherwise those aspects you point out probably should be dealt with as well.

**Comment by Fe1777** [comment]
It seems like you're dealing with the **Now in Android** project and working on a pull request titled "Dt/clean arch," potentially focusing on implementing or enhancing a Clean Architecture.

Here's a structured approach to manage this pull request:

### Understanding Clean Architecture

Clean Architecture aims to make the codebase more modular, maintainable, and testable. This involves a separation of concerns where the project is divided into different layers: Presentation, Domain, and Data layers. Each has its responsibilities and dependencies are directed from the outer layers to the inner layers.

### Common Steps to Implement Clean Architecture

1. **Define Layers:**
   - **Presentation Layer:** UI/UX components (Activities, Fragments, ViewModels).
   - **Domain Layer:** Business logic (UseCases, Interactors).
   - **Data Layer:** Data handling (Repositories, Data Sources, Network, and Database).

2. **Create Packages:**
   - Organize your code into the aforementioned layers. This helps maintain a clear structure.

3. **Interfaces and Dependency Injection:**
   - Use interfaces to decouple layers.
   - Implement Dependency Injection using libraries like Dagger or Hilt.

4. **Repository Pattern:**
   - Create repositories that will act as intermediaries between the Domain and Data layers.

### Example Pull Request Description

To give a comprehensive overview, your PR should be clear on what changes were made and why. Here’s an example:

**Title:** Implementing Clean Architecture

**Body:**
```
## Description

This pull request refactors the project structure to follow Clean Architecture principles. The goal is to improve maintainability, testability, and scalability by separating concerns into Presentation, Domain, and Data layers.

## Changes

- **Presentation Layer:**
  - Created packages for `ui`, `viewmodels`, and `activities`.
  - Updated ViewModels to interact with UseCases.

- **Domain Layer:**
  - Created `usecases` package.
  - Added UseCases to encapsulate business logic.

- **Data Layer:**
  - Created `repositories`, `datasources`, and `models`.
  - Implemented Repository pattern to handle data operations.

## Issues

This PR addresses the architectural restructuring and aims to solve issues related to code maintenance and scalability.

## Type of change
- [x] Refactoring (non-breaking change that improves the structure of the existing code)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- [x] Unit tests for each UseCase.
- [x] Integration tests for repositories and data sources.
- [x] Manual testing for Presentation layer components.

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Notes:
- This PR focuses on structural changes; functionality remains the same for end-users.
- Additional documentation has been added to the project to facilitate understanding of the new architecture.
```

### Useful Commands to Run

**Navigate to Your Project Directory:**
```sh
cd path/to/your/project
```

**Creating New Folders and Moving Files:**
```sh
mkdir -p app/src/main/java/com/yourproject/data
mkdir -p app/src/main/java/com/yourproject/domain
mkdir -p app/src/main/java/com/yourproject/presentation

# Move files to appropriate directories
mv app/src/main/java/com/yourproject/oldpath/* app/src/main/java/com/yourproject/data/
```

**Adding Dependencies in build.gradle (if needed for DI):**
```gradle
// For Dagger/Hilt
dependencies {
    implementation "com.google.dagger:hilt-android:<latest-version>"
    kapt "com.google.dagger:hilt-compiler:<latest-version>"
}
```

**Running Tests:**
```sh
./gradlew test
./gradlew connectedAndroidTest
```

**Committing Changes:**
```sh
git add .
git commit -m "Refactor project structure to Clean Architecture"
```

**Pushing to a Branch:**
```sh
git push origin dt/clean-arch
```

**Update Pull Request:**
- Navigate to GitHub to ensure your pull request from `dt/clean-arch` reflects your latest commits.
- Review and update PR description and title as needed.

By following these structured steps, you can effectively manage and communicate the changes involving Clean Architecture in your project.

**Comment by dturner** [comment]
This isn't something we're looking to support/merge for now. If you wish to investigate a clean architecture version of this project please do it on your own fork.

**Pull request closed without merging**
