### PR TITLE
Enable gradle type-safe project accessors and replace all occurrences

### LINKED ISSUE #638: [FR]: Use Gradle type-safe project accessors
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I discovered in issue #319 that `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")` has been removed from `build-logic` because it was not being used. 

However, it has never been added to the root project file `settings.gradle.kts`, and as a result, the current code is not robust against naming changes.

```kotlin
dependencies {
    implementation(project(":feature:interests"))
    implementation(project(":feature:foryou"))
    implementation(project(":feature:bookmarks"))
}
```

### Describe the solution

We should introduce `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")`. This will improve readability and maintainability of the project by using a more consistent way to reference other modules.

With the [gradle type-safe project accessors](https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors), the above code snippet can be replaced with:
```kotlin
dependencies {
    implementation(projects.feature.interests)
    implementation(projects.feature.foryou)
    implementation(projects.feature.bookmarks)
}
```

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Xsims**
Closes #638

### CODE REVIEW

**Comment by Xsims** [comment]
CLA has been signed

**Comment by lihenggui** [comment]
I saw this project include some dependencies in the convention plugin. Do we need to change it?

https://github.com/android/nowinandroid/blob/main/build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt#L46

**Comment by Xsims** [comment]
> I saw this project include some dependencies in the convention plugin. Do we need to change it?
> 
> https://github.com/android/nowinandroid/blob/main/build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt#L46

Only works in `build.gradle.kts` file for me

**Comment by tunjid** [comment]
@zsmb13 this looks good to me, is it good to merge?

**Comment by zsmb13** [comment]
I don't have strong feelings on this, it's quiet nice but it is still an incubating Gradle feature. Perhaps @borisf can comment on whether it makes sense for a sample to recommend it, or if it's too early.

**Comment by borisf** [comment]
Thanks Marton, Gradle type-safe project accesossors are incubating , thus have some rough edges https://github.com/gradle/gradle/issues?q=is%3Aopen+is%3Aissue+label%3Ain%3Aproject-accessors

**Comment by dturner** [comment]
The added benefit of type safety and IDE autocomplete seem to outweigh the "rough edges" so decided to add this in https://github.com/android/nowinandroid/pull/958.

**Pull request closed without merging**
