### PR TITLE
Reuse NiaGradientBackground from ForYouScreen on InterestsScreen

### LINKED ISSUE #13: [Bug]: `ForYouScreen` and `InterestsScreen` TopAppBar background color
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

`ForYouScreen` and `InterestsScreen` are not using the same background color:

| `ForYouScreen` | `InterestsScreen` | Diff |
|---|---|---|
| image | image | 0atetime%-diff |

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SimonMarquis**
Fixes #13

| `ForYouScreen` | `InterestsScreen` | Diff |
|---|---|---|
| Screenshot_20220512_231038 | Screenshot_20220512_231050 | 20220512-231110-diff |

### CODE REVIEW

**Comment by dturner** [comment]
Thanks so much for this PR, and for taking the time to include screenshots. We will review shortly.

**Comment by dturner** [comment]
This will fix internal issue b/232400367

**Comment by JolandaVerhoef** [comment]
This is not the right solution for the issue. Our designs use differently colored backgrounds for the two screens when in light mode. The For You screen uses a gradient background, and the Interests screen a solid background. In dark mode, both of them should be Surface-colored with an elevation of 2dp.

**Comment by JolandaVerhoef** [comment]
As mentioned in the latest comment, this solution is not in line with the designs. I will close this PR for now, feel free to create a new one!

**Pull request closed without merging**
