### PR TITLE
Use typesafe project accessor

### PR DESCRIPTION
**Pull request by AdnanHabibMirza**
Ensures consistent use of typesafe project accessors.

### CODE REVIEW

**Comment by AdnanHabibMirza** [comment]
CLA has been signed.

**Comment by nqmgaming** [comment]
@AdnanHabibMirza I’m not sure how the project can use the version catalog to reference and manage the modules in the Android project. Could you guide me on this?

**Comment by AdnanHabibMirza** [comment]
@nqmgaming You can use the Gradle feature preview `TYPESAFE_PROJECT_ACCESSORS` to achieve this.

To enable it, add the following line to your project's `settings.gradle.kts`:  
`enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")`.

You can find a list of all available Gradle feature previews here:
https://github.com/gradle/gradle/blob/v8.11.1/subprojects/core/src/main/java/org/gradle/api/internal/FeaturePreviews.java

**Comment by nqmgaming** [comment]
@AdnanHabibMirza  ah thank you 😁

**Review by dturner — APPROVED** [review]

**Pull request merged**
