### PR TITLE
Fix Bug #41 | Nia Naming conventions

### LINKED ISSUE #41: [Bug]: Consistent naming convention for NiANetwork and NiaPreferences etc
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Not a bug per se, and probably super picky :) , but be nice to have consistent naming convention e.g. for `NiANetwork` (big A) and `NiaPreferences` (little a)....only noticed this when reading https://github.com/android/nowinandroid/blob/main/docs/ArchitectureLearningJourney.md as I didn't realise initially  what `NiA` stood for!

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #45: [Filename Sanity]: NiAApp.kt vs ui/NiaApp.kt
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

In app/src/main/java/com/google/samples/apps/nowinandroid/ there is NiAApp.kt, whereas in ui/ there's NiaApp.kt.
Since one of the the app's goals is to "showcase best practices", maybe one of those files should be renamed? (hopefully not to the other's, but to a new unique name?)

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sud007**
Fix #41  Fix #45

> Made naming convention of classes/object and files starting with 'nia' (Now in Android) symmetrical, as 'Nia' instead of 'NiA' since, the former sounds more subtle and easy to follow in camel-case notation based naming for Files and Classes and objects while writing code.
> Also NiA vs Nia change was having less number of files getting affected.

### CODE REVIEW

**Comment by alexvanyo** [comment]
This is awesome! And the decision for correcting the naming (`Nia`) is what our team agreed upon as well (that aligns with the guidance around acronyms here: https://kotlinlang.org/docs/coding-conventions.html#choose-good-names)

It looks like the new names means the import orders changed which caused CI to fail, if you run `./gradlew spotlessApply` that should auto-fix those issues.

**Comment by sud007** [comment]
> This is awesome! And the decision for correcting the naming (`Nia`) is what our team agreed upon as well (that aligns with the guidance around acronyms here: https://kotlinlang.org/docs/coding-conventions.html#choose-good-names)
> 
> It looks like the new names means the import orders changed which caused CI to fail, if you run `./gradlew spotlessApply` that should auto-fix those issues.

Thanks for the review. really Appreciate.
updated as per the review suggestion

**Comment by dturner** [comment]
The CI build is failing due to missing database schemas, which are required for database migrations. Looks like you need to rename the folder: 

```
core-database/schemas/com.google.samples.apps.nowinandroid.core.database.NiADatabase
```

to 

```
core-database/schemas/com.google.samples.apps.nowinandroid.core.database.NiaDatabase
```

**Comment by sud007** [comment]
> The CI build is failing due to missing database schemas, which are required for database migrations. Looks like you need to rename the folder:
> 
> ```
> core-database/schemas/com.google.samples.apps.nowinandroid.core.database.NiADatabase
> ```
> 
> to
> 
> ```
> core-database/schemas/com.google.samples.apps.nowinandroid.core.database.NiaDatabase
> ```

@dturner Fixed and tested on local with success for CheckLint

**Review by alexvanyo — APPROVED** [review]
LGTM!

**Comment by alexvanyo** [comment]
Thanks for the contribution!

**Pull request merged**
