### PR TITLE
Reduce overall build complexity

### LINKED ISSUE #745: [FR]: Remove unnecessary dependencies requested by `AndroidFeatureConventionPlugin`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

The convention plugin [AndroidFeatureConventionPlugin](https://github.com/android/nowinandroid/blob/main/build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt) currently requests many dependencies.

https://github.com/android/nowinandroid/blob/b91773d05358fee6cbc64bc9de90817522399a3d/build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt#L45-L67

And I don't think this should be enforced for each module applying this plugin as not all features will need `:core:analytics`, or `coil` for instance.
This creates unnecessary dependencies and makes the dependency graph more complex than it needs to be.

### Describe the solution

Would that be ok to keep only the necessary dependencies, and move the others on each module that actually needs it?

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SimonMarquis**
- Reduce the visibility of multiple Hilt `Module`s and implementations of public interfaces
- Correctly configure the visibility of dependencies:
  - `api` when it's part of it's public `api`
  - `implementation` when it's part of it's internal `implementation`
- Remove unnecessary dependencies in build.gradle.kts files
- Remove unnecessary dependencies provided by plugins
- Remove unnecessary applied plugins (i.e. roborazzi)
- Sort dependencies in `build.gradle.kts`
- Delete unused entries in `libs.versions.toml`

This could still be improved by splitting the "tests" modules (like `:core:testing`) that currently exposes way too many dependencies, and by merging `testFixtures` sourceSets as explained in #451.

---

Here is the before/after for the build graph:

```diff
- GraphStatistics(modulesCount=25, edgesCount=102, height=7, longestPath=':app -> :feature:search -> :feature:bookmarks -> :core:ui -> :core:domain -> :core:data -> :core:database -> :core:model')
+ GraphStatistics(modulesCount=25, edgesCount=71, height=6, longestPath=':app -> :feature:search -> :feature:foryou -> :core:domain -> :core:data -> :core:database -> :core:model')
```

| Before | After |
|---|---|
| graph | graph (1) |

And here are some more useful stats, thanks to https://github.com/cdsap/ProjectGraphMetrics:

```diff
 ┌───────────────────────┬──────────┬──────────┬───────────────────────┬────────┐
 │ Module                │ Indegree │ Outdegre │ BetweennessCentrality │ Height │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :app                  │        0 │       13 │                   0.0 │      7 │
+│ :app                  │        0 │       13 │                   0.0 │      6 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :app-nia-catalog      │        0 │        2 │                   0.0 │      5 │
+│ :app-nia-catalog      │        0 │        2 │                   0.0 │      2 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:analytics       │       11 │        0 │                   0.0 │      0 │
+│ :core:analytics       │        5 │        0 │                   0.0 │      0 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:common          │       15 │        0 │                   0.0 │      0 │
+│ :core:common          │        7 │        0 │                   0.0 │      0 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:data            │       12 │        7 │                  72.0 │      2 │
+│ :core:data            │       12 │        6 │                  77.5 │      2 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:data-test       │        0 │        3 │                   0.0 │      5 │
+│ :core:data-test       │        0 │        1 │                   0.0 │      3 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:database        │        1 │        1 │                   0.0 │      1 │
+│ :core:database        │        1 │        1 │                   1.0 │      1 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:datastore       │        3 │        3 │                  16.5 │      1 │
+│ :core:datastore       │        2 │        3 │                  16.0 │      1 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
 │ :core:datastore-proto │        1 │        0 │                   0.0 │      0 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:datastore-test  │        0 │        3 │                   0.0 │      5 │
+│ :core:datastore-test  │        0 │        2 │                   0.0 │      2 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
 │ :core:designsystem    │       10 │        0 │                   0.0 │      0 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:domain          │        8 │        2 │                  14.0 │      3 │
+│ :core:domain          │        3 │        2 │                   1.5 │      3 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:model           │       16 │        0 │                   0.0 │      0 │
+│ :core:model           │        8 │        0 │                   0.0 │      0 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:network         │        1 │        2 │                   0.0 │      1 │
+│ :core:network         │        1 │        2 │                   1.0 │      1 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:notifications   │        2 │        2 │                   0.0 │      1 │
+│ :core:notifications   │        2 │        2 │                   1.0 │      1 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:testing         │        3 │        7 │                  14.5 │      4 │
+│ :core:testing         │        0 │        6 │                   0.0 │      3 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :core:ui              │        8 │        4 │                 10.14 │      4 │
+│ :core:ui              │        8 │        3 │                   9.5 │      1 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :feature:bookmarks    │        2 │        7 │                  0.14 │      5 │
+│ :feature:bookmarks    │        2 │        3 │                   0.0 │      3 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :feature:foryou       │        2 │        7 │                  0.14 │      5 │
+│ :feature:foryou       │        2 │        4 │                  0.33 │      4 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :feature:interests    │        2 │        7 │                  0.14 │      5 │
+│ :feature:interests    │        2 │        4 │                  0.33 │      4 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :feature:search       │        1 │       10 │                  0.14 │      6 │
+│ :feature:search       │        1 │        7 │                  0.33 │      5 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :feature:settings     │        1 │        7 │                  0.14 │      5 │
+│ :feature:settings     │        1 │        3 │                   0.0 │      3 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :feature:topic        │        1 │        7 │                  0.14 │      5 │
+│ :feature:topic        │        1 │        3 │                   0.0 │      3 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :sync:sync-test       │        0 │        3 │                   0.0 │      5 │
+│ :sync:sync-test       │        0 │        2 │                   0.0 │      4 │
 ├───────────────────────┼──────────┼──────────┼───────────────────────┼────────┤
-│ :sync:work            │        2 │        5 │                   3.0 │      3 │
+│ :sync:work            │        2 │        2 │                   0.5 │      3 │
 └───────────────────────┴──────────┴──────────┴───────────────────────┴────────┘
```

Closes #745

### CODE REVIEW

**Comment by lihenggui** [comment]
Just curious, how did you draw the dependency graph of these modules?

**Comment by SimonMarquis** [comment]
I think these ones (with the red critical path) have been generated with [jraska/modules-graph-assert](https://github.com/jraska/modules-graph-assert), but you can also use [siggijons/graph-untangler-plugin](https://github.com/siggijons/graph-untangler-plugin) to get more insight (critical graph).

**Comment by dturner** [comment]
Great work here @SimonMarquis. Did you use a dependency analyser (e.g. https://github.com/autonomousapps/dependency-analysis-gradle-plugin) to figure out which dependencies could be removed/restricted or was it all manual analysis? 

For my own reference (and anyone else who is interested) here's what I did to create the dependency information: 

Add the following to the root `build.gradle.kts`: 

```
plugins {
     id("com.jraska.module.graph.assertion") version "2.5.0"
...
}
```

Install GraphViz using `brew install graphviz`

Run the following command to analyse the module dependencies and generate a text file which can be read by GraphViz: 

```
./gradlew generateModulesGraphvizText -Pmodules.graph.output.gv=module_dependency_graph.gv
```

Convert the text file to an SVG

```
dot -Tsvg module_dependency_graph.gv > module_dependency_graph.svg
```

You can also get the statistics for the graph by running `generateModulesGraphStatistics`

**Comment by dturner** [comment]
For some reason the module graphs from the PR description aren't displaying when clicked. Adding them again here:  

| Before | After |
| --- | --- |
| module_dependency_graph_before | module_dependency_graph_after |

**Comment by SimonMarquis** [comment]
> Did you use a dependency analyser to figure out which dependencies could be removed/restricted or was it all manual analysis?

No, not really. IIRC I was browsing the build-logic's plugins and figured out there was too many unrelated dependencies added in some of them. We had the same kind of issued at my company, and having 1k+ modules had a big impact. Then I simply removed every dependency that was not obvious, and added one by one until everything compiles again.

[dependency-analysis-gradle-plugin](https://github.com/autonomousapps/dependency-analysis-gradle-plugin) is very nice, and there is a task to "automagically" fix these issues, but it never worked globally in practice in our code base.
Though it's nice to see, module-by-module, what is actually used or not, and the proper api visibility it should declare for its dependencies.
This is something that still confuses a lot of Android engineers since the move from old Gradle `compile` configuration to `implementation/api`.

PS: There are many online dot file viewers if you don't want to install graphviz on your computer :)

**Comment by dturner** [comment]
@mmoczkowski FYI we should discuss whether to enforce rules for the module graph (more info:  https://proandroiddev.com/module-rules-protect-your-build-time-and-architecture-d1194c7cc6bc)

**Review by dturner — APPROVED** [review]

**Comment by JoseAlcerreca** [comment]
This PR broke Roborazzi tests.

**Pull request merged**
