### PR TITLE
Typo fix for search & Remove the redundant "interests" prefix

### PR DESCRIPTION
**Pull request by anasshamsi97**
#500 interests_top_app_bar_action_seearch is misspelled in strings.xml which should actually be interests_top_app_bar_action_search. According to TODO task remove the redundant "interests" prefix in string.xml.

### CODE REVIEW

**Review by dturner — APPROVED** [review]
Thanks for doing this. Approved.

**Review by alexvanyo — APPROVED** [review]
Looks good, although spotless is throwing an error in CI.

Could you run `./gradlew --init-script gradle/init.gradle.kts spotlessApply` to hopefully fix that up?

**Comment by anasshamsi97** [comment]
Hi, the error was due to invalid file format of strings.xml. I've fixed the format and commit it.

**Comment by anasshamsi97** [comment]
@dturner @alexvanyo Thanks for approving and merging my pull request.

**Pull request merged**
