### PR TITLE
[Maintenance] Added new action to free up space - fix for CI

### PR DESCRIPTION
**Pull request by LinX64**
**What I have done and why**
What I have done and why Just added a new action to free up some space to make the CI work again.

This fixes the CI.

**Do tests pass?**
- [x] Run local tests on `DemoDebug` variant: `./gradlew testDemoDebug`
- [x] Check formatting: `./gradlew --init-script gradle/init.gradle.kts spotlessApply`

**Is this your first pull request?**
- [x] [Sign the CLA](https://cla.developers.google.com/)
- [x] Run `./tools/setup.sh`
- [x] Import the code formatting style as explained in [the setup script](/tools/setup.sh#L40).

### CODE REVIEW

**Comment by lihenggui** [comment]
The CI fails because it keeps waiting for the emulator to boot. It doesn't relate to the storage IMO

**Comment by LinX64** [comment]
> ~The CI fails because it keeps waiting for the emulator to boot. It doesn't relate to the storage IMO~
> 
> ```
> Starting emulator.
>   /usr/bin/sh -c \/usr/local/lib/android/sdk/emulator/emulator -avd test -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none &
>   INFO    | Android emulator version 33.1.24.0 (build_id [112](https://github.com/lihenggui/blocker/actions/runs/7834227158/job/21395493855#step:9:115)37101) (CL:N/A)
>   INFO    | Found systemPath /usr/local/lib/android/sdk/system-images/android-26/default/x86_64/
>   ERROR   | Not enough space to create userdata partition. Available: 4092.660156 MB at /home/runner/.android/avd/../avd/test.avd, need 7372.800000 MB.
>   INFO    | Storing crashdata in: , detection is enabled for process: 2801
>   INFO    | Duplicate loglines will be removed, if you wish to see each individual line launch with the -log-nofilter flag.
>   INFO    | Increasing RAM size to 1536MB
>   /usr/local/lib/android/sdk/platform-tools/adb shell getprop sys.boot_completed
>   * daemon not running; starting now at tcp:5037
>   * daemon started successfully
>   adb: no devices/emulators found
> ```

First of all, thanks for your comment, but there is a DO NOT REVIEW in the title. This PR is only for testing.

However, the CI issue now is more about Spotless, rather than the runner itself. Not sure if Spotless is working correctly, but I can see it fails because of the formatting in the `ForYouScreen` @dturner.

Anyways; by checking your public repo (blocker) I can see you've been facing that issue also:

>  ERROR   | Not enough space to create userdata partition. Available: 6178.628906 MB at /home/runner/.android/avd/../avd/test.avd, need 7372.800000 MB.

I could fix this by cleaning up the space on one of my repos. Unfortunately, I cannot re-run the build to prove that its working here as well. @dturner

**Comment by lihenggui** [comment]
> > ~The CI fails because it keeps waiting for the emulator to boot. It doesn't relate to the storage IMO~
> > ```
> > Starting emulator.
> >   /usr/bin/sh -c \/usr/local/lib/android/sdk/emulator/emulator -avd test -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none &
> >   INFO    | Android emulator version 33.1.24.0 (build_id [112](https://github.com/lihenggui/blocker/actions/runs/7834227158/job/21395493855#step:9:115)37101) (CL:N/A)
> >   INFO    | Found systemPath /usr/local/lib/android/sdk/system-images/android-26/default/x86_64/
> >   ERROR   | Not enough space to create userdata partition. Available: 4092.660156 MB at /home/runner/.android/avd/../avd/test.avd, need 7372.800000 MB.
> >   INFO    | Storing crashdata in: , detection is enabled for process: 2801
> >   INFO    | Duplicate loglines will be removed, if you wish to see each individual line launch with the -log-nofilter flag.
> >   INFO    | Increasing RAM size to 1536MB
> >   /usr/local/lib/android/sdk/platform-tools/adb shell getprop sys.boot_completed
> >   * daemon not running; starting now at tcp:5037
> >   * daemon started successfully
> >   adb: no devices/emulators found
> > ```
> 
> First of all, thanks for your comment, but there is a **DO NOT REVIEW** in the title. This PR is only for testing.
> 
> ~However, the CI issue now is more about Spotless, rather than the runner itself. Not sure if Spotless is working correctly, but I can see it fails because of the formatting in the `ForYouScreen`.~
> 
> Anyways; by checking your public repo (blocker) I can see you've been facing that issue also:
> 
> > ERROR   | Not enough space to create userdata partition. Available: 6178.628906 MB at /home/runner/.android/avd/../avd/test.avd, need 7372.800000 MB.
> 
> I could fix this by cleaning up the space on one of my repos. I'll give it a second try. Also, there will be a need for removing the caches in the runner -> caches as well. I don't have access to this, so maybe someone can take care of that. @dturner

At that time I was comparing the issues of NIA and my project, so I posted the wrong log, but the issue is the same. Sorry for the disrubtion.

I've confirmed that moving `Free Up GitHub Actions Ubuntu Runner Disk Space` job to the `androidTest` part can fix the CI issue. 

I will delete my useless discussion soon. Have a good time!

**Comment by LinX64** [comment]
> At that time I was comparing the issues of NIA and my project, so I posted the wrong log, but the issue is the same. Sorry for the disrubtion.
> 
> I've confirmed that moving `Free Up GitHub Actions Ubuntu Runner Disk Space` job to the `androidTest` part can fix the CI issue.
> 
> I will delete my useless discussion soon. Have a good time!

I'm glad it worked for you :) However, please remember that adding this action might increase the build time, and I suggest we create a scheduled job so that we make it more efficient.

**Comment by JoseAlcerreca** [comment]
Thanks for the PR but it has what seems like remnants of another change and the comment about a cron job makes no sense to me, so I'll close this one but use it an inspiration to fix CI which is broken right now.

Thanks!

**Pull request closed without merging**
