### PR TITLE
Remove `Stream` suffixes

### LINKED ISSUE #467: Remove `Stream` suffix from variable, function and UseCase names
This will improve code readability

### PR DESCRIPTION
**Pull request by zsmb13**
Fixes #467

### CODE REVIEW

**Review by dturner — APPROVED** [review]
That was quick - thanks!

**Comment by dev-weiqi** [comment]
should the [Recommendations for Android architecture ](https://developer.android.com/topic/architecture/recommendations#naming-conventions)be updated?


截圖 2022-12-06 17 15 43

**Comment by dturner** [comment]
It's optional so it's OK to leave that recommendation. It could still be useful in codebases which have a mix of reactive and imperative architectures.

**Comment by dev-weiqi** [comment]
@dturner Thank you for the detailed explanation 👍🏻

**Pull request merged**
