### PR TITLE
Fix Navigation Bar in landscape mode.

### LINKED ISSUE #59: [Bug]: Align the bottom bar items to center in the landscape mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

A bug happened when the device is on the landscape mode, the bottom bar items are moved to the top.

alt text

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by RivanParmar**
Fixes #59.

This is how it looks in landscape mode:

NowInAndroid

### CODE REVIEW

**Comment by RivanParmar** [comment]
This is how it looks in landscape mode:
NowInAndroid

**Comment by RivanParmar** [comment]
There were some mistakes in the first commit which I have corrected in the second commit https://github.com/android/nowinandroid/pull/68/commits/747416ad840c4f968fe70361c61b808c41a254b3. So please review and merge the second commit.

**Review by ricknout — APPROVED** [review]

**Comment by JolandaVerhoef** [comment]
Can you please check the failing build?

**Review by ricknout — APPROVED** [review]

**Comment by RivanParmar** [comment]
@JolandaVerhoef I have fixed the failing builds.

**Comment by RivanParmar** [comment]
@JolandaVerhoef Is it working now? As I am able to build and test the project in Android Studio without any errors.

**Comment by JolandaVerhoef** [comment]
You should run `./gradlew spotlessApply` to fix syntax errors in your code. Currently the build fails because the code contains syntax errors.

**Comment by RivanParmar** [comment]
@JolandaVerhoef The ```:app:spotlessKotlin``` is failing when I run ```./gradlew spotlessApply```. What should I do now?

**Comment by alexvanyo** [comment]
It looks like the line for those conditionals is too long, and `spotlessApply` isn't automatically line breaking them. You'll have to do that manually.

**Pull request merged**
