### PR TITLE
Create `Compose compiler metrics` permanent run configuration

### PR DESCRIPTION
**Pull request by SimonMarquis**
This will help devs run the right command, and it's easier to find.

image

### CODE REVIEW

**Comment by SimonMarquis** [comment]
I'm also wondering if it really makes sense to compile both `demo` and `prod` build types.
Shouldn't it focus only on the `prodRelease` variant?

**Comment by SimonMarquis** [comment]
🔔 @mmoczkowski this is a followup on
- #898

Also, do you have any opinion on my previous comment? (`assembleProdRelease`/`assembleDemoRelease` vs `assembleRelease`)

**Comment by dturner** [comment]
I'm not sure that an extra run configuration is necessary here but I'll defer to the Compose team. @bentrengrove what do you think about this approach - is it overkill?

**Comment by bentrengrove** [comment]
Unfortunately, I think this is overkill. There shouldn't be any issue just keeping it permanently enabled. Also, with strong skipping mode coming out soon we don't want to encourage manually annotating too many classes as stable, the compiler reports will still be useful but shouldn't be needed as much as now.

**Comment by SimonMarquis** [comment]
Ok, let's close this then 🫡

**Pull request closed without merging**
