### PR TITLE
Use App configuration as default configuration for the project

### PR DESCRIPTION
**Pull request by JolandaVerhoef**

### CODE REVIEW

**Comment by alexvanyo** [comment]
Latest change still doesn't seem to work on my side. Create a fresh clone of the project directly via command line, checked out this branch, then opened in AS EE Canary 9, and after sync finished `app-nia-catalog` was still the first entry in the run configuration.

**Comment by JolandaVerhoef** [comment]
Can you try one more time?

Steps to reproduce:
- Fresh clone of the project
- Open Android Studio, **File > New > Import project...**
- Your project should have 2 configurations, `app` and `design catalog`

**Comment by alexvanyo** [comment]
Result with the latest changes:

- Fresh clone, checkout this branch
- Open project
- While project is syncing, the 2 configurations are `app` and `design catalog`, with `app` selected
- Once syncing completes, there are 3 configurations: `app`, `design catalog` and `app-nia-catalog`, with `app-nia-catalog` selected

**Comment by dturner** [comment]
Just retested this and had the same result as @alexvanyo. `app-nia-catalog` is the default run configuration. 

image

**Comment by mmoczkowski** [comment]
Closing due to inactivity

**Pull request closed without merging**
