### PR TITLE
fix the bottom bar items alignment

### PR DESCRIPTION
**Pull request by SaeedNoshadi89**
This is related to #59 

device-2022-05-24-013314

### CODE REVIEW

**Comment by SaeedNoshadi89** [comment]
@JolandaVerhoef can this PR to review?

**Comment by JolandaVerhoef** [comment]
The design defines that the Navigation Bar and Rail should behave as defined by default by the Material 3 component. We do not want to adapt it's behavior, so if there's anything wrong with it we should raise a bug with the library. 

In this case, our design actually tells us that in Landscape mode, the app should still use the Navigation Bar and not switch to the Navigation Rail. So the actual solution to the issue you raised might be to do a better check on landscape / portrait.

**Comment by RivanParmar** [comment]
But the Material 3 documentation even states that the Navigation Bar should not be used for less than 3 destination instead we should use tabs. As shown [here](https://m3.material.io/components/navigation-bar/guidelines).

**Comment by RivanParmar** [comment]
Also I would like to work on it.

**Comment by JolandaVerhoef** [comment]
Good point, and you're right about the fact that the Navigation Bar should not be used for less than 3 destinations. However, we're planning to add more destinations in this bar, which is why we already opted to use a Navigation Bar although that does not follow the recommendations. 

A Navigation Bar is always horizontal. A Navigation Rail is vertical. In our designs, the landscape version of the app uses the same horizontal Navigation Bar as the portrait version. 

Feel free to re-open this Pull Request if you want to continue working on fixing the landscape version of the app, or open a new Pull Request with the changes instead!

**Comment by RivanParmar** [comment]
Ok, Thanks!

**Comment by RivanParmar** [comment]
@JolandaVerhoef I have created a new pull request #68 which fixes this issue and uses the same Navigation Bar in landscape mode. Please review it.

**Pull request closed without merging**
