### PR TITLE
Add NiaTopicTag chip interaction

### PR DESCRIPTION
**Pull request by yveskalume**
https://user-images.githubusercontent.com/55670723/201496584-fd8dff25-2d70-4fb3-b273-cb9b45412a57.mp4

### CODE REVIEW

**Comment by yveskalume** [comment]
Tests succeeded on my computer 🤔

**Comment by mmoczkowski** [comment]
Retrying build to see if it failed due to flakiness

**Comment by mmoczkowski** [comment]
Thank you for your contribution Yves. 

@dturner is this aligned with our design specs?

**Review by mmoczkowski — COMMENTED** [review]
Code looks good and straightforward to me. But I'd like someone else to confirm.

**Comment by calren** [comment]
I think we should hold off on merging this one.

I previously took out this functionality because it's not accessible by design. Following / Unfollowing a topic causes the whole screen to refresh.

**Comment by calren** [comment]
@yveskalume

Instead of having a drop down menu for the topic chips, what do you think about just navigating to browse the topic if the topic chip is clicked on? That would be a more accessible user experience.

**Comment by yveskalume** [comment]
I also think it's the best idea. 
So can I do that ?

**Comment by calren** [comment]
@yveskalume if you can update this PR to do what's described in https://github.com/android/nowinandroid/pull/429#issuecomment-1317610260, that'd be great!

**Comment by yveskalume** [comment]
@calren it's done !

**Comment by calren** [comment]
Hmm it looks like there are some files included in the diff that's not part of this PR, probably because of the merge with `main` branch? Do you mind getting that sorted out? Feel free to just open a new PR with your changes if that's easier.

**Comment by yveskalume** [comment]
Great, so let's close this one !

**Comment by yveskalume** [comment]
@calren I've open #444

**Pull request closed without merging**
