### PR TITLE
Introduce Gradle Managed Devices + Automated Test Device

### PR DESCRIPTION
**Pull request by thagikura**
- Update the AGP to 7.3.0-beta05 because it's needed for GMD
- Introduce GMD + ATD for a single module at first (core-database)

By running "./gradlew pixel4Api30DebugAndroidTest", the instrumented
tests of core-database are executed using the device configurations
specified in the build script.

### CODE REVIEW

**Comment by JoseAlcerreca** [comment]
Hey Takeshi, this requires moving to a beta version of AGP, which is a pretty big change just for GMD.

**Comment by thagikura** [comment]
Ok, let me wait for the AGP becomes stable, thanks.

**Comment by alexvanyo** [comment]
7.3.0 just released, this should be unblocked once we update.

**Comment by alexvanyo** [comment]
@thagikura a request for the PR: Could it be opened from a branch within the project and not from a fork?

I believe for security purposes the new workflow won't be run from a PR from a fork, and this is definitely one we want to make sure is passing before merging.

**Comment by thagikura** [comment]
Hi Alex, 

Ok, I'll open a new branch instead of a forked repository.
Thanks!

**Comment by dturner** [comment]
What's the status of this PR please? Should we merge it and run our API30 instrumented tests using GMD + ATD [instead of reactivecircus](https://github.com/android/nowinandroid/blob/main/.github/workflows/Build.yaml#L93)?

**Comment by mmoczkowski** [comment]
Closing this PR due to inactivity. If you still wish to submit this change, please create a new PR.

**Comment by dturner** [comment]
There's a request from the GMD team to reintroduce this into the project. 

@thagikura would you be able to update to AGP 7.3.0 and merge this please? We can then evaluate whether GMD is less flaky than using reactivecircus.

**Comment by thagikura** [comment]
Ok, I'll check if GMD works with AGP 7.3.0.
This PR was from the forked repository.
I'll try it with the same repository in another branch.

**Comment by thagikura** [comment]
Closing this in favor of https://github.com/android/nowinandroid/pull/479 to run GitHub Actions from the same repository instead of a forked repository.

**Pull request closed without merging**
