### PR TITLE
fix bottombar selected icon after navigate to subscreen

### PR DESCRIPTION
**Pull request by SaeedNoshadi89**
This is related to #17 
This issue happens in the landscape mode too

device-2022-05-20-171316

### CODE REVIEW

**Comment by SaeedNoshadi89** [comment]
@JolandaVerhoef can this pull request be merged?

**Comment by JolandaVerhoef** [comment]
The build is still failing, can you check it?

**Comment by SaeedNoshadi89** [comment]
> The build is still failing, can you check it?

Done

**Comment by dturner** [comment]
The merge conflict must be resolved before this PR can be merged - @SaeedNoshadi89 can you take a look?

**Comment by SaeedNoshadi89** [comment]
> The merge conflict must be resolved before this PR can be merged - @SaeedNoshadi89 can you take a look?

Done

**Comment by SaeedNoshadi89** [comment]
@simona-anomis Can this PR to review?

**Comment by simona-anomis** [comment]
Hi, thanks for raising it, this was already fixed in the latest set of changes, but thanks for helping out!

**Pull request closed without merging**
