### PR TITLE
Add dependency graphs to every module

### LINKED ISSUE #180: [FR]: Provide a graph of the module structure
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Especially for someone newer to multi-modular apps, looking at all the modules on the top level of the project can be daunting.

### Describe the solution

It would be awesome if an always up-to-date graph of how the modules depend on each other could be shown in the README of this repository.

### Additional context

I was recently reading the article "Jetpack Compose — Before and after" from [Chris Banes](https://medium.com/androiddevelopers/jetpack-compose-before-and-after-8b43ba0b7d4f) and in that post, the section "The app" with the figure named "Graph of Tivi’s module structure. Generated using [Jake Wharton](https://twitter.com/JakeWharton)’s handy [Gradle task](https://github.com/JakeWharton/SdkSearch/blob/master/gradle/projectDependencyGraph.gradle)" is exactly what I am talking about. I hope you can refer to it for some inspiration.
This would give a visualization of how everything is structured in an instant without having to look at the gradle files of all modules.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mmoczkowski**
Closes #180

### CODE REVIEW

**Comment by dturner** [comment]
First, this is incredible! 

Second, nit: could we make the images smaller so they're easier to see on a single screen?

**Review by dturner — CHANGES_REQUESTED** [review]
Smaller images please, otherwise LGTM

**Comment by mmoczkowski** [comment]
Hey @dturner, I made the graphs smaller. Let me know if they need further adjustments!

**Comment by RicardoJiang** [comment]
May I ask , Are these images drawn manually or automatically generated?

**Comment by mmoczkowski** [comment]
> May I ask , Are these images drawn manually or automatically generated?  @mmoczkowski 

Hey, those were generated by a plugin. I'm planning to open source it at some point. Do you find the graphs useful?

**Comment by RicardoJiang** [comment]
> > May I ask , Are these images drawn manually or automatically generated?  @mmoczkowski
> 
> Hey, those were generated by a plugin. I'm planning to open source it at some point. Do you find the graphs useful?

I think the graphs are beautiful and easy to understand, but each diagram only includes the direct dependencies of the module(After all, We can see the direct dependencies of the current module directly in build.gradle)

people may prefer to see the overall structure of the project, but this makes the graphs complicated and difficult to understand, I think It's hard to choose between the two

All in all, looking forward to your open source plugin, good job

**Comment by yoonseopshin** [comment]
@mmoczkowski 
🙏🏼 🙏🏼 🙏🏼

**Comment by mtzhisham** [comment]
> > May I ask , Are these images drawn manually or automatically generated?  @mmoczkowski
> 
> Hey, those were generated by a plugin. I'm planning to open source it at some point. Do you find the graphs useful?

Hey @mmoczkowski, I think it's very helpful to generate these graphs from onboarding new developers to getting to maintain modules with respect to their dependencies, can't wait to try the plugin.

**Comment by miduch** [comment]
> can't wait to try the plugin.
+1

**Comment by miduch** [comment]
@mmoczkowski can you give any rough ETA when this plugin is open source? if this isn't going to happen in near future would you be able to give some guidelines to try create own? Thanks!

**Comment by niusounds** [comment]
I also want to use the plugin!

**Comment by madroidmaq** [comment]
> > > May I ask , Are these images drawn manually or automatically generated?  @mmoczkowski
> > 
> > 
> > Hey, those were generated by a plugin. I'm planning to open source it at some point. Do you find the graphs useful?
> 
> I think the graphs are beautiful and easy to understand, but each diagram only includes the direct dependencies of the module(After all, We can see the direct dependencies of the current module directly in build.gradle)
> 
> people may prefer to see the overall structure of the project, but this makes the graphs complicated and difficult to understand, I think It's hard to choose between the two
> 
> All in all, looking forward to your open source plugin, good job

@RicardoJiang  I use Jake Wharton's [projectDependencyGraph](https://github.com/JakeWharton/SdkSearch/blob/master/gradle/projectDependencyGraph.gradle) script generates a complete dependency graph of the project, the effect is roughly as follows, I hope it will help you


project dot

**Comment by nienienienie** [comment]
any update of the graph generator @mmoczkowski ?

**Comment by amineharbaouibnp** [comment]
@mmoczkowski any news about this graph plugin please ? we really look forward to try it, it will be a super useful tool

**Pull request merged**
