### PR TITLE
Update material3 with built-in insets support

### PR DESCRIPTION
**Pull request by alexvanyo**
Feedback for updated insets support in https://issuetracker.google.com/issues/243713323

### CODE REVIEW

**Review by dturner — APPROVED** [review]
Thanks. Much easier to read without all that boilerplate.

**Comment by dturner** [comment]
You'll need to rebase onto main before merging because of the `lintDebug` issue.

**Comment by joreilly** [comment]
I was looking to apply changes here to one of my own projects and noticed change in color of bottom bar after making it.....seems like same difference with NowInAndroid app (with these changes)....not sure if intentional?

Screenshot_20220928_160605
Screenshot_20220928_160630

**Comment by StylianosGakis** [comment]
That's very odd, why would the colors change after changing some inset-related code?
Does it by any chance have to do with the new `androidxComposeMaterial3` dependency bump instead? Have you found out what exactly is it that changes the colors?

**Comment by joreilly** [comment]
I think it's related to removal of `Surface(color = MaterialTheme.colorScheme.surface)`

**Comment by alexvanyo** [comment]
> I think it's related to removal of Surface(color = MaterialTheme.colorScheme.surface)

Yup that was the reason. Consulting with our designs, I've updated to match the style we want here. @dturner and @ricknout please take another look!

**Review by ricknout — APPROVED** [review]

**Pull request merged**
