### PR TITLE
Migrate from `java` to `kotlin` sourceSet directory

### PR DESCRIPTION
**Pull request by SimonMarquis**
> **Note** This will force most of other PRs to rebase.

- #309
- #520
- #622

Using this command: 
```bash
find . -depth -type d -name "java" -path "*/src/*" -exec git mv "{}" "{}"/../kotlin \;
```

Closing #436

### CODE REVIEW

**Comment by SimonMarquis** [comment]
What do you mean by full tool support?
The `kotlin` sourceSet has been working for years now.
Do you have a specific issue in mind?

**Comment by SimonMarquis** [comment]
🙏 Could we finally merge this PR?

**Comment by dturner** [comment]
@JoseAlcerreca I'm guessing you mean - is this fully supported by Android Studio? Is that correct?

**Comment by dturner** [comment]
Just tested this in AS Giraffe and everything (indexing, UI previews, builds) seems to work as intended. There were some existing bugs related to this (internal only: [b/273905575](https://b.corp.google.com/273905575), [b/249125762](https://b.corp.google.com/249125762)) which have been fixed (thanks @rosejr). 

Thanks for doing this @SimonMarquis.

**Comment by SimonMarquis** [comment]
Thanks! I'll proceed to update all my pending reviews that are now in conflict 👍

**Comment by dawidhyzy** [comment]
Quick question. Is there a way to make `kotlin` sourceSet default when creating a new module?

**Pull request merged**
