### PR TITLE
Extract `ProfileVerifier` logs from `MainActivity` to `NiaApplication`

### LINKED ISSUE #945: [Bug]: `logCompilationStatus()` called multiple time
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

`MainActivity.logCompilationStatus()` is currently called from the `onResume()` lifecycle callback.

https://github.com/android/nowinandroid/blob/151f877bbe6546c78f8f03f16e56564e285fb508/app/src/main/java/com/google/samples/apps/nowinandroid/MainActivity.kt#L152-L158

And therefore might be called multiple times unnecessarily.
This is the case with the notifications permissions dialog for example, which puts the app in a paused state.

It would make more sense to move this log inside the `NiaApplication` class.
WDYT? I can prepare a PR for that if needed.

### Relevant logcat output

```
09-14 20:00:45.194 11708 11899 D ProfileInstaller: Installing profile for com.google.samples.apps.nowinandroid
09-14 20:00:45.215 11708 11851 D MainActivity: ProfileInstaller status code: 1
09-14 20:00:45.215 11708 11851 D MainActivity: ProfileInstaller: is compiled with profile
09-14 20:00:45.215 11708 11781 D MainActivity: ProfileInstaller status code: 1
09-14 20:00:45.215 11708 11781 D MainActivity: ProfileInstaller: is compiled with profile
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SimonMarquis**
- Prevent logging multiple times (because of `onResume()` callback)
- Remove unnecessary io dispatcher: `ListenableFuture<T>.await()` is already main-safe and prevent acquiring io slot.
- Merge comments into a single javadoc comment on the `ProfileVerifierLogger` type.
- Add proper javadoc format with markdown specific blocks.
- Update logs & tag to be more uniform.

Closes #945

### CODE REVIEW

**Comment by dturner** [comment]
Makes sense to me, however, I'd like @yenerm and/or @keyboardsurfer to review as there may be a reason why the profile compilation status was being logged inside `onResume` that isn't immediately apparent.

**Review by keyboardsurfer — APPROVED** [review]

**Comment by SimonMarquis** [comment]
@dturner, do we need to wait for yenerm's review? If not, this PR is ready to be merged. 😃

**Comment by SimonMarquis** [comment]
🔔 @dturner @keyboardsurfer 🙈

Seems like we are go to merge this? Is there anything left to do before merging it?

**Comment by keyboardsurfer** [comment]
Thanks for the nudge. I'm okay with merging this one but will leave the final decision to @dturner.

**Review by dturner — APPROVED** [review]

**Pull request merged**
