### PR TITLE
Add module dependencies graph

### PR DESCRIPTION
**Pull request by jisungbin**
Add a module dependencies graph image to help understand modularity.

For me, seeing the module dependencies graph was a big help in understanding the modularization relationships in NIA. 
I'm adding the image I referenced to the project README in case it helps others as much as it did me.
This change is simply my wish, so please feel free to close this pull request. If you don't agree, feel free to close this.

Thanks.

### CODE REVIEW

**Comment by SimonMarquis** [comment]
IMO the dependency graph used in the app module is more readable https://github.com/android/nowinandroid/blob/main/docs/images/graphs/dep_graph_app.png

**Comment by dturner** [comment]
Yes, this was the purpose of the module dependency images. The issue is that these images go out of date when the dependencies change because it's an unlinked manual process to generate and update them (using an Android Studio plugin).  

@mmoczkowski Is there any way to automate the dependency image generation, perhaps through a commit hook?

**Comment by SimonMarquis** [comment]
This could be easily be ran as a GitHub Action if the script to generate these images is made public :)

**Comment by SimonMarquis** [comment]
There is also this graph I just discovered in the "modularization journey": https://github.com/android/nowinandroid/blob/main/docs/images/modularization-graph.drawio.png

I don't know exactly how it was produced, be it seems it's handcrafted, even though it could be "fairly easy" to reproduce with a Gradle plugin.

**Comment by jisungbin** [comment]
Hi! Thanks for the review. I've checked out all reviews and I agree. I thought didn't need this change anymore, so I closed it. Thanks.

**Pull request closed without merging**
