### PR TITLE
[UI Polish] Adjusted spacing based on design spec

### PR DESCRIPTION
**Pull request by c5inco**
Tweaked spacing on a couple components and screens to align with the design spec.

**For You screen**
image

**Saved/Bookmarks screen**
image

**Interests screen**
image

### CODE REVIEW

**Comment by LinX64** [comment]
Thanks for taking care of this! Looks good after your changes!

**Review by alexvanyo — APPROVED** [review]
LGTM, also checked the changes visually fullscreen on a tablet.

**Comment by dturner** [comment]
Hey @c5inco, thanks for doing this. Would you be able to resolve the conflicts? Or if not possible, push your changes onto a branch named `cs/ui-polish` on this repo so that one of the team can resolve and merge.

**Comment by c5inco** [comment]
@dturner conflicts resolved!

**Pull request merged**
