### PR TITLE
Rewrite all UI tests with the Robot design pattern #401

### PR DESCRIPTION
**Pull request by JanFidor**
All tests have been rewritten with robot design pattern with no changes to the inner logic of the test (the only exception being bookmarks feature -> feed_whenRemovingBookmark_removesBookmark() test. I believe that my change allows for more flexibility with testing multiple bookmark deletions)

### CODE REVIEW

**Comment by dturner** [comment]
Thanks for this PR. Please run 

```
./gradlew --init-script gradle/init.gradle.kts spotlessApply
```

to fix formatting issues, and also resolve the merge conflicts.

**Comment by JanFidor** [comment]
Hi! Thanks for the quick script, it definitely saved me a lot of time. I'm terribly grateful for the opportunity to contribute here, unfortunately I might have gotten a little to enthusiastic about it and messed up git history a bit (sorry, I'll make sure not to do that next time) but everything's working and the gradle script throws up no errors.

**Comment by mmoczkowski** [comment]
Waiting for author to update PR

**Comment by JanFidor** [comment]
CI checks seem to be failing due to com.google.samples.apps.nowinandroid.ui.NavigationTest -> navigationBar_reselectTab_keepsState test. I've tried a lot of things (included but not limited to clearing my gradle cache) but I can't reproduce it on my machine, more importantly, my PR didn't change that file, so the CI checks seem to be the problem, could anyone confirm?

**Pull request closed without merging**
