### PR TITLE
removed suppression for plugin applications with alias

### LINKED ISSUE #654: [Cleanup] Remove suppression for plugin applications with alias once updated to Gradle 8.1
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

#35 added suppression for using the `alias` to apply plugins from `libs.versions.toml`.

In Gradle 8.1, this workaround is no longer necessary: https://docs.gradle.org/8.1-rc-1/userguide/upgrading_version_8.html#kotlin_dsl_plugins_catalogs_workaround

Once we update to Gradle 8.1, we'll be able to remove those suppressions.

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gururani-abhishek**
closes #654 

1. In Gradle 8.1, this workaround will no longer be necessary.

### CODE REVIEW

**Comment by alexvanyo** [comment]
The update to AGP 8.1 was merged, so this PR should be mergable now on top of main once the conflicts are resolved.

**Comment by gururani-abhishek** [comment]
> The update to AGP 8.1 was merged, so this PR should be mergable now on top of main once the conflicts are resolved.

Resolved conflicts :)

**Comment by gururani-abhishek** [comment]
Found something related to this build fail : https://github.com/google/protobuf-gradle-plugin/issues/687

**Comment by rosejr** [comment]
Thanks for the PR; this has been done in https://github.com/android/nowinandroid/pull/667

**Pull request closed without merging**
