### PR TITLE
Add testing section to pull_request_template.md

### PR DESCRIPTION
**Pull request by JoseAlcerreca**
Making testing a bit more mandatory.

### CODE REVIEW

**Comment by Jaehwa-Noh** [comment]
You just edit ```pull_request_template.md```, but why test coverage report shows ❌?

**Comment by JoseAlcerreca** [comment]
> You just edit `pull_request_template.md`, but why test coverage report shows ❌?

You can ignore it. It's an x if the coverage is <40% right now.  We'll probably disable it if no files with coverage are involved.

**Comment by Jaehwa-Noh** [comment]
The base line would be 39.97% now, aren't you? Why set 40%?
You've expected this project test coverage will over 40% so you set that?

**Comment by JoseAlcerreca** [comment]
I just don't think overall coverage is a useful metric, but it's interesting to see how it evolves over time.

**Comment by Jaehwa-Noh** [comment]
Aha, I agree with you. Thank you.

**Review by dturner — APPROVED** [review]

**Pull request merged**
