### PR TITLE
Update kotlin 1.7.21

### LINKED ISSUE #438: [Bug]: Warning message ksp-1.7.21-1.0.8 is too new for kotlin-1.7.20
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

```
ksp-1.7.21-1.0.8 is too new for kotlin-1.7.20. Please upgrade kotlin-gradle-plugin to 1.7.21.
```

Example in GitHub Actions: https://github.com/android/nowinandroid/actions/runs/3473866639/jobs/5806381926#step:9:23

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SimonMarquis**
Fixes #438

### CODE REVIEW

**Comment by SimonMarquis** [comment]
This was reverted here https://github.com/android/nowinandroid/commit/f896a8c50d41a0f79deb8a90e3130876d0d5367d but for no apparent reason in the commit message.
@mmoczkowski what was the issue?
If this needs to be 1.7.20 for now, we should revert ksp as well.

**Comment by SimonMarquis** [comment]
Seems to be related to Compose compiler:
`e: This version (1.3.2) of the Compose Compiler requires Kotlin version 1.7.20 but you appear to be using Kotlin version 1.7.21 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).`

https://github.com/android/nowinandroid/actions/runs/3473373873/jobs/5805326415#step:8:242

**Comment by SimonMarquis** [comment]
Support for Kotlin 1.7.21 was added in [1.4.0-alpha02](https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.4.0-alpha02).

**Comment by SimonMarquis** [comment]
Here is the "scary" warning message in the current build: https://github.com/android/nowinandroid/actions/runs/3473866639/jobs/5806381926#step:9:23

**Comment by mmoczkowski** [comment]
Hey Simon, thanks for the PR, but let's wait until stable version of Compose compiler supports 1.7.21

**Comment by SimonMarquis** [comment]
Should we instead rollback ksp to make this scary warning message disappear?

**Pull request closed without merging**
