### PR TITLE
Critical path graph

### PR DESCRIPTION
**Pull request by SimonMarquis**
project
project_critical_path

### CODE REVIEW

**Comment by SimonMarquis** [comment]
- #310

🛎️ @mmoczkowski it would be very helpful to surface this kind of information, and especially in the style of rendering you were able to produce in this PR.
I'd love to see it open-sourced here.
If you need some help to clean things up, to fix bugs, or to simply iron things out, I'd love to help make it happen 🙏

**Comment by SimonMarquis** [comment]
This graph also show that `:feature:search` depends on other feature modules: `:feature:bookmarks`, `:feature:foryou`, `:feature:interests`, which should be prohibited.

**Comment by SimonMarquis** [comment]
For example, this [`1993d52` (#870)](https://github.com/android/nowinandroid/pull/870/commits/1993d52327d3e901e80889950c9e40a7bf989b0e) will update the critical graph to:

analyzeModuleGraph-height gv

**Comment by keyboardsurfer** [comment]
Thank you for submitting this pull request. We have decided not to accept it at this time.
Feel free to comment or open an issue for further discussion if necessary.

**Pull request closed without merging**
