### PR TITLE
Upgrade Gradle to v8.3

### PR DESCRIPTION
**Pull request by lihenggui**
Gradle v8.3 release note: https://docs.gradle.org/8.3/release-notes.html

Elimination of deprecated usage `Project.getBuildDir()`: 
https://github.com/gradle/gradle/issues/20210
https://docs.gradle.org/8.3/userguide/upgrading_version_8.html#project_builddir

### CODE REVIEW

**Comment by SimonMarquis** [comment]
@lihenggui Can you also make sure the corresponding Gradle wrapper JAR is updated.
The expected sha256 is `0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15` according to https://gradle.org/release-checksums/

**Comment by lihenggui** [comment]
> @lihenggui Can you also make sure the corresponding Gradle wrapper JAR is updated. The expected sha256 is `0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15` according to https://gradle.org/release-checksums/
> 
> You can run this command again to force downloading the latest wrappers:
> 
> ```shell
> ./gradlew wrapper
> ```

Checked and updated

image

**Comment by lihenggui** [comment]
@alexvanyo @dturner  @tunjid Ping

**Review by dturner — APPROVED** [review]
Thanks for doing this.

**Pull request merged**
