### PR TITLE
Enable DEX layout optimizations

### LINKED ISSUE #992: [Bug]: Dex Layout reordering requires non-minified benchmark build
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

We can enable Dex layout reordering to use startup profiles. To use them, the benchmark build needs to have `isMinifyEnabled = false`.

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SimonMarquis**
- [X] Disable minification
- [X] Enable `android.experimental.r8.dex-startup-optimization`
- [x] ~Copy~ Move `app/src/main/baseline-prof.txt` to `src/main/baselineProfiles/startup-prof.txt`

Closes #992

### CODE REVIEW

**Comment by keyboardsurfer** [comment]
Thanks for spinning this up, @SimonMarquis! This change also requires AGP 8.2 as well as calling `includeInStartupProfile = true` in the most basic startup baseline profile generator.

**Comment by SimonMarquis** [comment]
@keyboardsurfer it seems like `R8Task` currently looks for a `app/baselineProfiles/startup-prof.txt` by default.
There are at least 4 solutions for that:
- duplicate `app/src/main/baseline-prof.txt` to `src/main/baselineProfiles/startup-prof.txt`
- move `app/src/main/baseline-prof.txt` to `src/main/baselineProfiles/startup-prof.txt`
- create a symlink between `app/src/main/baseline-prof.txt` and `src/main/baselineProfiles/startup-prof.txt`
- configure the `R8Task`
What would be the best option here?

> This change also requires AGP 8.2

Do you mean it won't work on the current AGP 8.1.2? Because it does compile correclty and seems to use the `startup-prof.txt` when provided.

> as well as calling includeInStartupProfile = true in the most basic startup baseline profile generator.

ACK, done in https://github.com/android/nowinandroid/pull/1020/commits/aeac096c6b06ac11eb58dc47754f29d5b1ec12d5

**Comment by keyboardsurfer** [comment]
The startup-prof.txt will be generated from the generator which has `includeInStartupProfile = true`.
In the long run we want to fully remove the source files and rely on the baseline profile Gradle plugin to generate fresh profiles for each release.

**Comment by SimonMarquis** [comment]
> The startup-prof.txt will be generated from the generator which has `includeInStartupProfile = true`.

Indeed, running `:benchmarks:connectedDemoBenchmarkAndroidTest` leads to a `startup-prof.txt` being generated (extracted from logcat)

```
2023-11-06 22:11:59.015 23686-23703 Benchmark               com....apps.nowinandroid.benchmarks  D  Moving /storage/emulated/0/Android/media/com.google.samples.apps.nowinandroid.benchmarks/BaselineProfileGenerator_generate-startup-prof.txt to /sdcard/Android/media/com.google.samples.apps.nowinandroid.benchmarks/additional_test_output/BaselineProfileGenerator_generate-startup-prof.txt
2023-11-06 22:11:59.029 23686-23703 Benchmark               com....apps.nowinandroid.benchmarks  D  Pull Baseline Profile with: `adb pull "/storage/emulated/0/Android/media/com.google.samples.apps.nowinandroid.benchmarks/BaselineProfileGenerator_generate-startup-prof-2023-11-06-21-11-59.txt" .`
2023-11-06 22:11:59.037 23686-23703 Benchmark               com....apps.nowinandroid.benchmarks  D  Moving /storage/emulated/0/Android/media/com.google.samples.apps.nowinandroid.benchmarks/BaselineProfileGenerator_generate-startup-prof-2023-11-06-21-11-59.txt to /sdcard/Android/media/com.google.samples.apps.nowinandroid.benchmarks/additional_test_output/BaselineProfileGenerator_generate-startup-prof-2023-11-06-21-11-59.txt
```

Unfortunately, nothing is being actually generated on my device 🤷 the directories do not exist...

> In the long run we want to fully remove the source files and rely on the baseline profile Gradle plugin to generate fresh profiles for each release.

Does that mean the release process will need to spawn an emulator and run the tests before compiling/packaging the app? (this might be hard to implement correctly and reliably)

**Comment by keyboardsurfer** [comment]
> Does that mean the release process will need to spawn an emulator and run the tests before compiling/packaging the app? (this might be hard to implement correctly and reliably)

This is best done with the baseline profile gradle plugin. It'll take care of the entire process.

> Unfortunately, nothing is being actually generated on my device 🤷 the directories do not exist...

This is really strange. Which device are you using? Does it work when using a Gradle Managed Device instead?

**Pull request closed without merging**
